DROP PROCEDURE IF EXISTS _mig;
CREATE PROCEDURE _mig() BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE players ADD COLUMN note VARCHAR(255) NOT NULL DEFAULT '';
END;
CALL _mig();
DROP PROCEDURE IF EXISTS _mig;
