DROP PROCEDURE IF EXISTS _mig;
CREATE PROCEDURE _mig() BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE legions ADD COLUMN warehouse_kinah BIGINT NOT NULL DEFAULT 0;
END;
CALL _mig();
DROP PROCEDURE IF EXISTS _mig;
