DROP PROCEDURE IF EXISTS _mig;
CREATE PROCEDURE _mig() BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE players ADD COLUMN abyss_points BIGINT NOT NULL DEFAULT 0;
    ALTER TABLE players ADD COLUMN abyss_rank   INT    NOT NULL DEFAULT 1;
END;
CALL _mig();
DROP PROCEDURE IF EXISTS _mig;
