-- Aion Lightning 4.6.0 — game server schema (minimal M5 subset)
-- Full schema: AL-Game/sql/al_server_gs.sql

CREATE TABLE IF NOT EXISTS `players` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `account_id` int(11) NOT NULL,
  `account_name` varchar(50) NOT NULL,
  `exp` bigint(20) NOT NULL DEFAULT '0',
  `recoverexp` bigint(20) NOT NULL DEFAULT '0',
  `x` float NOT NULL DEFAULT '0',
  `y` float NOT NULL DEFAULT '0',
  `z` float NOT NULL DEFAULT '0',
  `heading` int(11) NOT NULL DEFAULT '0',
  `world_id` int(11) NOT NULL DEFAULT '210010000',
  `world_owner` int(11) NOT NULL DEFAULT '0',
  `gender` enum('MALE','FEMALE') NOT NULL DEFAULT 'MALE',
  `race` enum('ASMODIANS','ELYOS') NOT NULL DEFAULT 'ELYOS',
  `player_class` enum('WARRIOR','GLADIATOR','TEMPLAR','SCOUT','ASSASSIN','RANGER','MAGE','SORCERER','SPIRIT_MASTER','PRIEST','CLERIC','CHANTER','ENGINEER','GUNNER','ARTIST','BARD','RIDER','ALL') NOT NULL DEFAULT 'WARRIOR',
  `creation_date` timestamp NULL DEFAULT NULL,
  `deletion_date` timestamp NULL DEFAULT NULL,
  `last_online` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `quest_expands` tinyint(1) NOT NULL DEFAULT '0',
  `npc_expands` tinyint(1) NOT NULL DEFAULT '0',
  `advanced_stigma_slot_size` tinyint(1) NOT NULL DEFAULT '0',
  `warehouse_size` tinyint(1) NOT NULL DEFAULT '0',
  `title_id` int(3) NOT NULL DEFAULT '-1',
  `bonus_title_id` int(3) NOT NULL DEFAULT '-1',
  `dp` int(3) NOT NULL DEFAULT '0',
  `online` tinyint(1) NOT NULL DEFAULT '0',
  `security_token` varchar(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_unique` (`name`),
  KEY `account_id` (`account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `player_appearance` (
  `player_id` int(11) NOT NULL,
  `face` int(11) NOT NULL DEFAULT '0',
  `hair` int(11) NOT NULL DEFAULT '0',
  `deco` int(11) NOT NULL DEFAULT '0',
  `tattoo` int(11) NOT NULL DEFAULT '0',
  `face_contour` int(11) NOT NULL DEFAULT '0',
  `expression` int(11) NOT NULL DEFAULT '0',
  `jaw_line` int(11) NOT NULL DEFAULT '0',
  `skin_rgb` int(11) NOT NULL DEFAULT '0',
  `hair_rgb` int(11) NOT NULL DEFAULT '0',
  `lip_rgb` int(11) NOT NULL DEFAULT '0',
  `eye_rgb` int(11) NOT NULL DEFAULT '0',
  `face_shape` int(11) NOT NULL DEFAULT '0',
  `forehead` int(11) NOT NULL DEFAULT '0',
  `eye_height` int(11) NOT NULL DEFAULT '0',
  `eye_space` int(11) NOT NULL DEFAULT '0',
  `eye_width` int(11) NOT NULL DEFAULT '0',
  `eye_size` int(11) NOT NULL DEFAULT '0',
  `eye_shape` int(11) NOT NULL DEFAULT '0',
  `eye_angle` int(11) NOT NULL DEFAULT '0',
  `brow_height` int(11) NOT NULL DEFAULT '0',
  `brow_angle` int(11) NOT NULL DEFAULT '0',
  `brow_shape` int(11) NOT NULL DEFAULT '0',
  `nose` int(11) NOT NULL DEFAULT '0',
  `nose_bridge` int(11) NOT NULL DEFAULT '0',
  `nose_width` int(11) NOT NULL DEFAULT '0',
  `nose_tip` int(11) NOT NULL DEFAULT '0',
  `cheek` int(11) NOT NULL DEFAULT '0',
  `lip_height` int(11) NOT NULL DEFAULT '0',
  `mouth_size` int(11) NOT NULL DEFAULT '0',
  `lip_size` int(11) NOT NULL DEFAULT '0',
  `smile` int(11) NOT NULL DEFAULT '0',
  `lip_shape` int(11) NOT NULL DEFAULT '0',
  `jaw_height` int(11) NOT NULL DEFAULT '0',
  `chin_jut` int(11) NOT NULL DEFAULT '0',
  `ear_shape` int(11) NOT NULL DEFAULT '0',
  `head_size` int(11) NOT NULL DEFAULT '0',
  `neck` int(11) NOT NULL DEFAULT '0',
  `neck_length` int(11) NOT NULL DEFAULT '0',
  `shoulders` int(11) NOT NULL DEFAULT '0',
  `shoulder_size` int(11) NOT NULL DEFAULT '0',
  `torso` int(11) NOT NULL DEFAULT '0',
  `chest` int(11) NOT NULL DEFAULT '0',
  `waist` int(11) NOT NULL DEFAULT '0',
  `hips` int(11) NOT NULL DEFAULT '0',
  `arm_thickness` int(11) NOT NULL DEFAULT '0',
  `arm_length` int(11) NOT NULL DEFAULT '0',
  `hand_size` int(11) NOT NULL DEFAULT '0',
  `leg_thickness` int(11) NOT NULL DEFAULT '0',
  `leg_length` int(11) NOT NULL DEFAULT '0',
  `foot_size` int(11) NOT NULL DEFAULT '0',
  `facial_rate` int(11) NOT NULL DEFAULT '0',
  `voice` int(11) NOT NULL DEFAULT '0',
  `height` float NOT NULL DEFAULT '1.0',
  PRIMARY KEY (`player_id`),
  CONSTRAINT `player_appearance_ibfk_1` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
