DROP PROCEDURE IF EXISTS _mig;
CREATE PROCEDURE _mig() BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE `players` ADD COLUMN `current_hp` INT UNSIGNED NULL DEFAULT NULL;
    ALTER TABLE `players` ADD COLUMN `current_mp` INT UNSIGNED NULL DEFAULT NULL;
END;
CALL _mig();
DROP PROCEDURE IF EXISTS _mig;
