DROP PROCEDURE IF EXISTS _mig;
CREATE PROCEDURE _mig() BEGIN
    DECLARE CONTINUE HANDLER FOR 1060 BEGIN END;
    ALTER TABLE players ADD COLUMN abyss_gp          BIGINT NOT NULL DEFAULT 0;
    ALTER TABLE players ADD COLUMN abyss_daily_gp    BIGINT NOT NULL DEFAULT 0;
    ALTER TABLE players ADD COLUMN abyss_weekly_gp   BIGINT NOT NULL DEFAULT 0;
    ALTER TABLE players ADD COLUMN abyss_last_gp     BIGINT NOT NULL DEFAULT 0;
    ALTER TABLE players ADD COLUMN abyss_top_ranking INT    NOT NULL DEFAULT 0;
END;
CALL _mig();
DROP PROCEDURE IF EXISTS _mig;
