<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(DotNetVersion)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AionServer.Commons\AionServer.Commons.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="$(ExtensionsVersion)"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="Scripts\**\*.cs">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <!-- Don't remove, let Rider analyze but exclude from build -->
        <Compile Update="Scripts\**\*.cs">
            <Visible>true</Visible>
        </Compile>
    </ItemGroup>

    <Target Name="RemoveScriptsFromBuild" BeforeTargets="BeforeBuild">
        <ItemGroup>
            <Compile Remove="Scripts\**\*.cs" />
        </ItemGroup>
    </Target>

</Project>
