using AionServer.Commons.Database;
using AionServer.Login.Models;

namespace AionServer.Login.Database;

public abstract class AccountDao : IDao
{
    /// <summary>
    /// Returns account by name or null
    /// </summary>
    /// <param name="name">account name</param>
    /// <returns>account object or null</returns>
    public abstract Account? GetAccount(string name);

    public abstract Account? GetAccount(int id);

    /// <summary>
    /// Returns account id or -1 in case of error
    /// </summary>
    /// <param name="name">name of account</param>
    /// <returns>id or -1 in case of error</returns>
    public abstract int GetAccountId(string name);

    /// <summary>
    /// Returns account count. If error occurred - returns -1
    /// </summary>
    /// <returns>account count</returns>
    public abstract int GetAccountCount();

    /// <summary>
    /// Inserts new account to database. Sets account ID to id that was generated by DB.
    /// </summary>
    /// <param name="account">account to insert</param>
    /// <returns>true if was inserted, false in other case</returns>
    public abstract bool InsertAccount(Account account);

    /// <summary>
    /// Updates account in database
    /// </summary>
    /// <param name="account">account to update</param>
    /// <returns>true if was updated, false in other case</returns>
    public abstract bool UpdateAccount(Account account);

    /// <summary>
    /// Updates lastServer field of account
    /// </summary>
    /// <param name="accountId">account id</param>
    /// <param name="lastServer">last accessed server</param>
    /// <returns>was updated successful or not</returns>
    public abstract bool UpdateLastServer(int accountId, byte lastServer);

    /// <summary>
    /// Updates last ip that was used to access an account
    /// </summary>
    /// <param name="accountId">account id</param>
    /// <param name="ip">ip address</param>
    /// <returns>was update successful or not</returns>
    public abstract bool UpdateLastIp(int accountId, string ip);

    /// <summary>
    /// Get last ip that was used to access an account
    /// </summary>
    /// <param name="accountId">account id</param>
    /// <returns>ip address</returns>
    public abstract string? GetLastIp(int accountId);

    /// <summary>
    /// Updates last mac that was used to access an account
    /// </summary>
    /// <param name="accountId">account id</param>
    /// <param name="mac">mac address</param>
    /// <returns>was update successful or not</returns>
    public abstract bool UpdateLastMac(int accountId, string mac);

    /// <summary>
    /// Updates account membership
    /// </summary>
    /// <param name="accountId">account id</param>
    /// <returns>was update successful or not</returns>
    public abstract bool UpdateMembership(int accountId);

    /// <summary>
    /// Deletion of all accounts, inactive for more than dayOfInactivity days
    /// </summary>
    /// <param name="daysOfInactivity"></param>
    public abstract void DeleteInactiveAccounts(int daysOfInactivity);

    /// <summary>
    /// Returns unique class name for all implementations
    /// </summary>
    /// <returns>unique class name for all implementations</returns>
    public string GetClassName()
    {
        return typeof(AccountDao).FullName ?? nameof(AccountDao);
    }

    public bool Supports(string databaseName, int majorVersion, int minorVersion)
    {
        return true;
    }
}