<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DotNetVersion)</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
        <PackageReference Include="Dapper" Version="2.1.35" />
        <PackageReference Include="Evolve" Version="3.1.0" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="$(ExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(ExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="$(ExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="$(ExtensionsVersion)" />
        <PackageReference Include="MySqlConnector" Version="2.3.7" />
        <PackageReference Include="Quartz" Version="3.15.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="$(ExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="$(ExtensionsVersion)" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
        <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    </ItemGroup>

</Project>
